# Merge several scRNA-seq datasets, discarding cells that do not pass QC.
#
# This script also ensures that cell names correspond to the names generated by
# cellranger agg. The latter program ensures unique barcodes across samples by
# numbering them like BARCODE-1 to BARCODE-10, using the order of samples in
# aggregation.csv. By contrast, Seurat (if data is loaded with Read10X_h5())
# uses the numbering system BARCODE-1_1 to BARCODE-1_10; sample indices
# correspond to the order of samples in c(x, y) of merge().
#
# Generates the file rna_merged.rds, which contains a Seurat object representing
# the merged, QC-filtered dataset.

library(Seurat)
library(tidyverse)
library(fs)



# Parameters --------------------------------------------------------------

# folder that contains cellranger results
data_dir <- "data_raw/COUNT"

# path where the merged dataset is saved
out_file <- "data_generated/rna_merged.rds"

# data frame with three columns 'order', 'sample_name', and 'sample_file'
samples <-
  tibble(
    sample_file = dir_ls(
      data_dir,
      recurse = TRUE,
      regexp = "filtered_feature_bc_matrix.h5"
    ),
    bsf_id = str_match(sample_file, "([\\w\\d_]*)_trans")[, 2]
  ) %>%
  left_join(
    read_csv("metadata/sample_groups.csv", comment = "#"),
    by = "bsf_id"
  ) %>% 
  arrange(bsf_order) %>% 
  select(order = bsf_order, sample_file, sample_name = sample) %>% 
  drop_na()

# QC parameters
max_percent_mt <- 10
min_n_feature <- 200
max_n_feature <- 5000



# Merge datasets ----------------------------------------------------------

nb_list <- pmap(
  samples,
  function(order, sample_file, sample_name) {
    message("Loading ", sample_name)
    sample_file %>% 
      Read10X_h5() %>% 
      magrittr::set_colnames(
        str_replace(colnames(.), "\\d+$", as.character(order))
      ) %>% 
      CreateSeuratObject(sample_name) %>% 
      AddMetaData(sample_name, col.name = "sample") %>%
      PercentageFeatureSet(pattern = "^MT-", col.name = "percent.mt") %>% 
      subset(
        subset =
          nFeature_RNA > min_n_feature &
          nFeature_RNA < max_n_feature &
          percent.mt < max_percent_mt
      )
  }
)

nb <- merge(nb_list[[1]], nb_list[-1])



# Save results ------------------------------------------------------------

saveRDS(nb, out_file)
