# Summarize tSNEs generated by Cell Ranger
# (i.e., as stored in [sample]/analysis/tsne/2_components/projection.csv)

library(tidyverse)
library(fs)
library(patchwork)



# Load data ---------------------------------------------------------------

df_tsne <- 
  dir_ls("data_raw", recurse = TRUE, regexp = "projection.csv") %>% 
  map_dfr(
    read_csv,
    col_names = c("barcode", "tsne1", "tsne2"),
    col_types = "cdd",
    skip = 1,
    .id = "file"
  ) %>%
  extract(
    file,
    into = c("sample", "method"),
    regex = "/[^_]*_(.*)_(ATAC|transcriptome)"
  ) %>% 
  {.}

df_cluster <- 
  dir_ls("data_raw", recurse = TRUE, regexp = "clusters.csv") %>% 
  map_dfr(
    read_csv,
    col_names = c("barcode", "cluster"),
    col_types = "ci",
    skip = 1,
    .id = "file"
  ) %>% 
  extract(
    file,
    into = c("sample", "method"),
    regex = "/[^_]*_(.*)_(ATAC|transcriptome)"
  ) %>% 
  {.}

df <- 
  df_tsne %>% 
  left_join(df_cluster, by = c("sample", "method", "barcode"))



# Cell plots --------------------------------------------------------------

# for testing
df %>% 
  filter(sample %in% c("16_4503_Re", "GNB_2014_0102")) %>%
  ggplot(aes(tsne1, tsne2)) +
  geom_point(aes(color = as_factor(cluster)), size = .1, show.legend = FALSE) +
  coord_fixed() +
  facet_grid(vars(method), vars(sample)) +
  NULL

first_row_samples <- unique(df$sample)[1:7]
second_row_samples <- unique(df$sample) %>% setdiff(first_row_samples)

plot_cells_rows <- function(row_samples) {
  df %>% 
    filter(sample %in% row_samples) %>%
    ggplot(aes(tsne1, tsne2)) +
    geom_point(
      aes(color = as_factor(cluster)),
      size = .1,
      show.legend = FALSE
    ) +
    xlim(-60, 60) +
    ylim(-60, 60) +
    coord_fixed() +
    facet_grid(vars(method), vars(sample)) +
    theme_bw() +
    theme(
      strip.background = element_blank(),
      strip.text = element_text(face = "bold")
    ) +
    NULL
}

(plot_cells_rows(first_row_samples) / plot_cells_rows(second_row_samples)) +
  plot_layout(guides = "collect") +
  plot_annotation(
    "Cell Ranger t-SNEs",
    caption = "cells colored by graph-based clusters"
  )

ggsave("plots/cellranger_summary/tsne_cells.pdf",
       units = "mm", width = 300, height = 210)



# Hexbin plots ------------------------------------------------------------

# for testing
df %>% 
  filter(sample %in% c("16_4503_Re", "GNB_2014_0102")) %>%
  ggplot(aes(tsne1, tsne2)) +
  geom_hex(bins = 50) +
  scale_fill_viridis_c(option = "B", direction = 1) +
  coord_fixed() +
  facet_grid(vars(method), vars(sample)) +
  NULL



plot_hexbin_rows <- function(row_samples) {
  df %>% 
    filter(sample %in% row_samples) %>%
    ggplot(aes(tsne1, tsne2)) +
    geom_hex(bins = 50) +
    xlim(-60, 60) +
    ylim(-60, 60) +
    scale_fill_viridis_c(option = "B", direction = 1, limits = c(0, 40)) +
    coord_fixed() +
    facet_grid(vars(method), vars(sample)) +
    theme_bw() +
    theme(
      strip.background = element_blank(),
      strip.text = element_text(face = "bold")
    ) +
    NULL
}

(plot_hexbin_rows(first_row_samples) / plot_hexbin_rows(second_row_samples)) +
  plot_layout(guides = "collect") +
  plot_annotation(
    "Cell Ranger t-SNEs",
    caption = "cells binned into 50 x 50 bins"
  )

ggsave("plots/cellranger_summary/tsne_hexbin.pdf",
       units = "mm", width = 300, height = 210)

